config/routes.rb
TodolistApp::Application.routes.draw do
  resources :lists do
   resources :tasks
  end
 

  root :to => 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  attr_accessible :name
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  def create
    @list = List.new(params[:list])
    respond_to do |format|
      if @list.save
        format.html { redirect_to action: :index, notice: 'New List has been created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def new
  end

  def create
  end

  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  def create
    @task = Task.new(params[:task])
    respond_to do |format|
      if @task.save
        format.html { redirect_to action: :index, notice: 'New task has been created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodolistApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/create.html.erb
<h1>List#create</h1>
<p>Find me in app/views/list/create.html.erb</p>

app/views/lists/index.html.erb
<h1>Existing Lists</h1>
<table>
  <tr>
    <th>List Name</th>
    <th>Date Created</th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.name %></td>
    <td><%= list.created_at.strftime("%D") %></td>
    <td><%= link_to 'Add Tasks', new_task_path %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

<%= form_for(@list) do |l| %>
  <div class="field">
    <%= l.label :name %><br />
    <%= l.text_field :name %>
  </div>

  <div class="actions">
    <%= l.submit %>
  </div>
<% end %>

app/views/tasks/create.html.erb
<h1>Task#create</h1>
<p>Find me in app/views/task/create.html.erb</p>

app/views/tasks/index.html.erb
<h1>Task#index</h1>
<p>Find me in app/views/task/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Task#new</h1>
<p>Find me in app/views/task/new.html.erb</p>
<h1>Adding tasks to (SPECIFY LIST)</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Date Created</th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.created_at.strftime("%D") %></td>
  </tr>
<% end %>
</table>

<br />



<%= link_to 'New List', new_list_path %>